### ISSUE TITLE
test code is wrong

### ISSUE THREAD

**Issue by k-suwabe** [CheckiO-Missions/checkio-mission-max-digit#6]
It seems the following test code is wrong.
The expected answer is 3, is not it?

https://github.com/CheckiO-Missions/checkio-mission-max-digit/blob/master/verification/tests.py
        {
            "input": [3053456],
            "answer": 6,
        }

**Comment by oduvan** [comment]
no.

3 is not the biggest digest is the number. There are 4,5 and 6 bigger than 3
